import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { TernSecureProvider } from '@tern-secure/nextjs';
import { ThemeProvider } from '@/components/theme-provider';
import { Header } from '@/components/header';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TernSecureProvider
          appName='TernSecure'
          appCheck={{
            provider: 'reCaptchaV3',
            siteKey: '6LfZFhcsAAAAAMX2kZwW5USvnwNrqEnj6lh3ogzr',
            isTokenAutoRefreshEnabled: true,
          }}
          requiresVerification={false}
          persistence='local'
          ternUIUrl='http://localhost:4000/ternsecure.browser.js'
          apiUrl='localhost:3000'
          //tenantId='lifesprintcare-zsqsk'
          //afterSignOutUrl='/sign-in'  //better use it on client-side
        >
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
          </ThemeProvider>
        </TernSecureProvider>
      </body>
    </html>
  );
}
