export { ternSecureMiddleware, createRouteMatcher } from './ternSecureNodeMiddleware'
export { auth, getUser, isAuthenticated, requireAuth, type AuthResult } from './auth'
export { auth as authNew, getUser as getUserNew, isAuthenticated as isAuthenticatedNew, requireAuth as requireAuthNew } from './auth-new'
export type { BaseUser, SessionResult } from './types'
export { NextCookieStore } from '../utils/NextCookieAdapter'