name: CI
on:
  merge_group:
  pull_request:
    branches:
      - main
      - changeset-release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  #check-permissions:
  pre-checks:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: Validate PR
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      TURBO_SUMMARIZE: false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup
        id: config
        uses: ./.github/actions/init
        with:
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
          turbo-summarize: ${{ env.TURBO_SUMMARIZE }}
          turbo-team: ${{ vars.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}

      - name: Require changeset
        if: ${{ !(github.event_name == 'merge_group') }}
        run: pnpm changeset status --since=origin/main

      - name: Turbo Build
        run: pnpm turbo build $TURBO_ARGS --only
        
      - name: Lint
        run: pnpm turbo lint
